//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotizador.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public long IdCotizacion { get; set; }
        public string codigoCotizacion { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
        public string Cliente { get; set; }
        public string Producto { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> SubtotalCotizacion { get; set; }
        public Nullable<decimal> PorcentajeComision { get; set; }
        public Nullable<decimal> ValorComision { get; set; }
        public Nullable<decimal> PorcentajeIva { get; set; }
        public Nullable<decimal> ValorIva { get; set; }
        public Nullable<decimal> TotalCotizacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<decimal> Version { get; set; }
    }
}
